
OBJ_DEPS = HepMcLoader.o NumpyFile.o Util.o DelphesRootLoader.o FastjetFinder.o

all: multijet_delphes multijet_hadronized multijet_hard

multijet_delphes: multijet_delphes.o $(OBJ_DEPS)
multijet_hadronized: multijet_hadronized.o $(OBJ_DEPS)
multijet_hard: multijet_hard.o $(OBJ_DEPS)
