# Data
particle_type: piplus
fixed_noise: False

# INN Training
lr: 5.e-5
max_lr: 5.e-4
batch_size: 256
lr_scheduler: one_cycle_lr
weight_decay: 0.
betas: [0.9, 0.999]
n_epochs: 400
save_interval: 10
keep_models: 100

# Bayesian Setup
bayesian: True
std_init: -9
prior_prec: 50.0

# INN Architecture
n_blocks: 12
internal_size: 32
layers_per_block: 3
coupling_type: rational_quadratic
bounds_init: 20
permute_soft: False
num_bins: 10
dropout: 0.0

# INN Preprocessing
use_extra_dim: False
use_extra_dims: True
use_norm: False
log_cond: True
alpha: 1.e-6

# Unit: Gev
width_noise: 1.e-6



# Classifier Test
do_classifier_test: True

# Classifier Training
classifier_sigmoid_in_BCE: True
classifier_lr: 2.e-4
classifier_n_epochs: 100
classifier_batch_size: 1000
classifier_runs: 5

# Classifier Architecture
modes: ["DNN"]
DNN_hidden_layers: 2
DNN_hidden_neurons: 512
DNN_dropout: 0.

# Classifier Preprocessing
classifier_threshold: True #needed
classifier_normalize: False #needed
classifier_use_logit: False #needed