run_name: eplus
no_cuda: False

# Data
train_split: 0.8
data_path: "../data/calo/eplus.hdf5"
width_noise: 1.e-7

# Training
lr: 1.e-5
max_lr: 1.e-4
batch_size: 512
lr_scheduler: one_cycle_lr
weight_decay: 0.
betas: [0.9, 0.999]
n_epochs: 50

# Architecture
n_blocks: 12
internal_size: 512
layers_per_block: 2
coupling_type: cubic
permute_soft: False
num_bins: 8
dropout: 0.05

# Preprocessing
use_extra_dim: True
use_norm: False
log_cond: False
alpha: 1.e-8
