run_name: eplus

# Data
train_split: 0.8
data_path: "../data/calo/eplus.hdf5"
width_noise: 1.e-7

# Training
lr: 1.e-4
max_lr: 3.e-4
batch_size: 512
lr_scheduler: one_cycle_lr
weight_decay: 0.
betas: [0.9, 0.999]
n_epochs: 50

# Architecture
n_blocks: 10
internal_size: 256
layers_per_block: 3
coupling_type: cubic
bounds_init: 20
permute_soft: False
num_bins: 10
dropout: 0.05

# Preprocessing
use_extra_dim: True
use_norm: False
log_cond: False
alpha: 1.e-8
