run_name: eplus_bayesian

# Data
train_split: 0.8
data_path: "../data/calo/eplus.hdf5"
width_noise: 8.e-8

# Training
lr: 5.e-4
max_lr: 1.e-3
batch_size: 512
lr_scheduler: one_cycle_lr
weight_decay: 0.
betas: [0.9, 0.999]
n_epochs: 600
save_interval: 100

# Architecture
n_blocks: 10
internal_size: 256
layers_per_block: 3
coupling_type: cubic
bounds_init: 20
permute_soft: False
num_bins: 10
dropout: 0.
bayesian: True
prior_prec: 500.0
std_init: -9.0

# Preprocessing
use_extra_dim: True
use_extra_dims: False
use_norm: False
log_cond: True
alpha: 2.e-8
