run_name: eplus_base_det
p_type: eplus
dtype: float32
# Data
train_split: 1.
train_data_path: "../datasets/train_eplus.hdf5"
test_data_path: "../datasets/test_eplus.hdf5"
width_noise: 1.e-6

# Training
lr: 1.e-5
max_lr: 1.e-4
batch_size: 64
lr_scheduler: one_cycle_lr
weight_decay: 0.
betas: [0.9, 0.999]
n_epochs: 150
save_interval: 10

# Architecture
n_blocks: 12
internal_size: 256
layers_per_block: 3
coupling_type: rational_quadratic
bounds_init: 20
permute_soft: False
permute_layer: False
num_bins: 10
dropout: 0.05
bias: True

# Preprocessing
use_extra_dims: True
use_norm: False
log_cond: True
alpha: 1.e-10
