run_name: full_training_det_u10_rew85_1e6
p_type: piplus
dtype: float32
# Data
data_path: /remote/gpu06/favaro/datasets/calo_challenge/piplus_data_1.hdf5
val_data_path: /remote/gpu06/favaro/datasets/calo_challenge/piplus_data_1.hdf5
xml_path: /remote/gpu06/favaro/datasets/calo_challenge/binning_dataset_1_pions.xml
single_energy: null
width_noise: 5.0e-6
custom_noise: False
val_frac: 0.01
eps: 1.0e-10
xml_ptype: "pion"
eval_dataset: "1-pions"
u0up_cut: 3.5
u0low_cut: 0.0
pt_rew: 1.0
dep_cut: 600

# Training
lr: 1.e-5
max_lr: 1.e-4
batch_size: 512

lr_scheduler: one_cycle_lr

weight_decay: 0.01
betas: [0.9, 0.999]
n_epochs: 10
cycle_epochs: 10
save_interval: 100

# Architecture
n_blocks: 12
internal_size: 256
layers_per_block: 4
coupling_type: rational_quadratic
bounds_init: 18
permute_soft: False
permute_layer: False
num_bins: 10
dropout: 0.0
bayesian: False
prior_prec: 5000
std_init: -15.0

sub_layers: [linear, linear, linear, linear]
norm: True
# Preprocessing
use_extra_dims: True
use_norm: False
log_cond: True
alpha: 1.0e-8
alpha_logit: 1.0e-6
