# General
# data_path: ... # TODO: Path to the data

# Documenter information
run_name: pions
vae_dir: null
# Data
dtype: float32
particle_type: pion
dataset: 1
val_frac: 0.2
eps: 1.e-10
threshold: 1.e-10


# VAE
VAE_type: CVAE
VAE_learnable_norm: False
# VAE Preprocessing
alpha: 1.e-6
VAE_internal_threshold: 1.e-8
# VAE Training
VAE_lr_scheduler: null
VAE_max_lr: 1.e-4
VAE_lr: 1.e-4
VAE_weight_decay: 1.e-7
VAE_batch_size: 256
VAE_n_epochs: 1000
VAE_save_interval: 50
VAE_keep_models: 3001
VAE_zero_logit: True # Set the logit loss to 0
sparsity_loss: null
VAE_smearing_self: 0.6
VAE_smearing_share: 0.05
# VAE Architecture
VAE_hidden_sizes: [5000, 1000, 500]
VAE_latent_dim: 50
VAE_beta: 1.e-5
VAE_gamma: 1.e+4


# INN

# INN Preprocessing
logit_transformation: False
log_transformation: False
log_cond: True
# INN Training
lr: 5.e-5
max_lr: 5.e-4
batch_size: 256
lr_scheduler: one_cycle_lr
weight_decay: 0.
betas: [0.9, 0.999]
n_epochs: 200
save_interval: 50
keep_models: 1000
# Bayesian Setup
bayesian: False
prior_prec: 5000
std_init: -15.0
# INN Architecture
n_blocks: 18
internal_size: 32
layer_act: nn.ReLU
layer_norm: null
layer_classes: [linear, linear, linear]
coupling_type: rational_quadratic
ActNorm: False
bounds_init: 20
permute_soft: False
num_bins: 10
dropout: 0.0
